INSERT INTO categoria (nome) VALUES ('Greca');
INSERT INTO categoria (nome) VALUES ('Italiana');
INSERT INTO categoria (nome) VALUES ('Messicana');
INSERT INTO categoria (nome) VALUES ('Fast Food');
INSERT INTO unita_di_misura (udm) VALUES ('grammi');
INSERT INTO unita_di_misura (udm) VALUES ('litri');
INSERT INTO unita_di_misura (udm) VALUES ('cucchiaio');
INSERT INTO unita_di_misura (udm) VALUES ('cucchiaino');
INSERT INTO unita_di_misura (udm) VALUES ('kili');
INSERT INTO unita_di_misura (udm) VALUES ('millilitri');